spring.application.name=itBovin

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bovin_db
spring.datasource.username=postgres
spring.datasource.password=etu003948

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port de l'application (optionnel)
server.port=8080


# Thymeleaf configuration
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# Optionnel : si vous utilisez une base de données, ajustez selon votre besoin
# spring.datasource.url=jdbc:mysql://localhost:3306/bovin_db
# spring.datasource.username=root
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update